untitled folder/routes/web.php
    <?php
    
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\Route;
    
    Auth::routes();
    
    
    Route::get('/', 'HomeController@index')->name('home');
    
    Route::group( ['prefix' => 'company-profile' ],
    
        function () {
            Route::get('/', 'Front\CompanyController@index')->name('company-profile');
            Route::get('chairman-report', 'Front\CompanyController@chairmanReport')->name('chairman-report');
            Route::get('business-principles', 'Front\CompanyController@principlesCode')->name('principles-code');
            Route::get('corporate-governance', 'Front\CompanyController@corporateGovernance')->name('corporate-governance');        
            Route::get('timeline', 'Front\CompanyController@timeline')->name('timeline');
            Route::get('board-of-directors', 'Front\CompanyController@boardOfDirectors')->name('board-of-directors');
            Route::get('management-team', 'Front\CompanyController@managementTeam')->name('management-team');
			Route::get('awards', 'Front\CompanyController@awards')->name('awards');
            }
    );

    Route::group( ['prefix' => 'management-team' ],
    
        function () {
        Route::get('/', 'Front\ManagementController@index')->name('management-team');
        Route::get('thanaphol-leelangamwong', 'Front\ManagementController@thanapholLeelangamwong')->name('thanaphol-leelangamwong');
        Route::get('santi-suanyot', 'Front\ManagementController@santiSuanyot')->name('santisuanyot');
        Route::get('phiphit-khlaisombat', 'Front\ManagementController@phiphitKhlaisombat')->name('phiphit-khlaisombat');
        Route::get('nattapong-dachanabhirom', 'Front\ManagementController@nattapongDachanabhirom')->name('nattapong-dachanabhirom');
        Route::get('palat-tittinutchanon', 'Front\ManagementController@palatTittinutchanon')->name('palat-tittinutchanon');
        Route::get('harry-brock', 'Front\ManagementController@harryBrock')->name('harry-brock');
        Route::get('john-clendon', 'Front\ManagementController@johnClendon')->name('john-clendon');
            
        }
    );
    
    Route::group( ['prefix' => 'directors' ],
    
        function () {
        Route::get('/', 'Front\DirectorsController@index')->name('directors');
        Route::get('apirag-vanich', 'Front\DirectorsController@apiragVanich')->name('apirag-vanich');
        Route::get('phortchana-manoch', 'Front\DirectorsController@phortchanaManoch')->name('phortchana-manoch');
        Route::get('kanchana-vanich', 'Front\DirectorsController@kanchanaVanich')->name('kanchana-vanich');
        Route::get('palat-tittinutchanon', 'Front\DirectorsController@palatTittinutchanon')->name('palat-tittinutchanon');
        Route::get('chantip-vanich', 'Front\DirectorsController@chantipVanich')->name('chantip-vanich');
        Route::get('prote-sosothikul', 'Front\DirectorsController@proteSosothikul')->name('prote-sosothikul');
        Route::get('john-clendon', 'Front\DirectorsController@johnClendon')->name('john-clendon');
        Route::get('suchad-chiaranussati', 'Front\DirectorsController@suchadChiaranussati')->name('suchad-chiaranussati');
        Route::get('supapang-chanlongbutra', 'Front\DirectorsController@supapangChanlongbutra')->name('supapang-chanlongbutra');
        Route::get('pramoad-phornprapha', 'Front\DirectorsController@pramoadPhornprapha')->name('pramoad-phornprapha');
        }
    );
    
    Route::group( ['prefix' => 'operations' ],
        function () {
            Route::get('/', 'Front\OperationsController@index')->name('operations');
            Route::get('estates', 'Front\OperationsController@estates')->name('estates');
            Route::get('factories', 'Front\OperationsController@factories')->name('factories');
            Route::get('nurseries', 'Front\OperationsController@nurseries')->name('nurseries');
        }
    );
    
    Route::group( ['prefix' => 'estates' ],
        function () {
            Route::get('/', 'Front\EstatesController@index')->name('estates');
            Route::get('topi', 'Front\EstatesController@topi')->name('topi');
            Route::get('siampalm', 'Front\EstatesController@siampalm')->name('siampalm');
            Route::get('akapojana', 'Front\EstatesController@akapojana')->name('akapojana');
            Route::get('nanua', 'Front\EstatesController@nanua')->name('nanua');
            Route::get('chauat', 'Front\EstatesController@chauat')->name('chauat');
            Route::get('pabon', 'Front\EstatesController@pabon')->name('pabon');
            Route::get('wannee', 'Front\EstatesController@wannee')->name('wannee');
            Route::get('lamthap', 'Front\EstatesController@lamthap')->name('lamthap');
            Route::get('cheanvanich', 'Front\EstatesController@cheanvanich')->name('cheanvanich');
            Route::get('khlongtom', 'Front\EstatesController@khlongtom')->name('khlongtom');
        }
    );
    
    Route::group( ['prefix' => 'products' ],
        function () {
    
            Route::get('/', 'Front\ProductsController@index')->name('products');
            Route::get('cpo-pko', 'Front\ProductsController@cpoPko')->name('cpo-pko');
            Route::get('seed-seedlings', 'Front\ProductsController@seedSeedlings')->name('seed-seedlings');
            Route::get('seeds', 'Front\ProductsController@seeds')->name('seeds');
            Route::get('seedlings', 'Front\ProductsController@seedlings')->name('seedlings');
            Route::get('biogas', 'Front\ProductsController@biogas')->name('biogas');
            Route::get('by-products', 'Front\ProductsController@byProducts')->name('by-products');
    
        }
    );
    
    Route::group( ['prefix' => 'investor-relations' ],
        function () {
        
            Route::get('/', 'Front\InvestorRelationsController@index')->name('investor-relations');
            Route::get('financial-information', 'Front\InvestorRelationsController@financialInformation')->name('financial-information');
            Route::get('shareholder', 'Front\InvestorRelationsController@shareholder')->name('shareholder');
            Route::get('publications', 'Front\InvestorRelationsController@publications')->name('publications');
        }
    
    );
    
    Route::group( ['prefix' => 'sustainability' ],
        function () {
            Route::get('/', 'Front\SustainabilityController@index')->name('sustainability');
            Route::get('social-sustainability', 'Front\SustainabilityController@social')->name('social');
            Route::get('environmental-sustainability', 'Front\SustainabilityController@environmental')->name('environmental');
            Route::get('economic-sustainability', 'Front\SustainabilityController@economic')->name('economic');
            Route::get('scientific-sustainability', 'Front\SustainabilityController@scientific')->name('scientific');
            Route::get('corporate-governance', 'Front\SustainabilityController@corporate')->name('corporate');
        }
    );
    
    Route::group( ['prefix' => 'media' ],
        function () {
            Route::get('/', 'Front\MediaController@index')->name('media');
            Route::get('news2008', 'Front\MediaController@news2008')->name('news2008');
            Route::get('news2007', 'Front\MediaController@news2007')->name('news2007');
            Route::get('news2006', 'Front\MediaController@news2006')->name('news2006');
        }
    );
    
    Route::group( ['prefix' => 'careers' ],
        function () {
            Route::get('/', 'Front\CareersController@index')->name('careers');
        }
    );
    
    Route::group( ['prefix' => 'contact-us' ],
        function () {
            Route::get('/', 'Front\ContactController@index')->name('contact');
            Route::get('whistleblowing', 'Front\ContactController@whistleblowing')->name('whistleblowing');
            Route::get('feedback-inquiries', 'Front\ContactController@feedbackInquiries')->name('feedback-inquiries');
        }
    );
    
    
    
    
    
    
    
    Route::get('company-awards', 'HomeController@companyAwards')->name('company-awards');
    Route::get('operation-map', 'HomeController@operationMap')->name('operation-map');
    
    Route::get('projects', 'HomeController@projects')->name('projects');
    Route::get('project-details', 'HomeController@projectDetails')->name('project-details');
    
    Route::group(
        [
            'prefix' => 'admin',
            'middleware' => ['auth']
        ],
        function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
    
            Route::resource('regions', 'RegionController');
            Route::resource('status', 'ProjectStatusController');
            Route::resource('projects', 'ProjectController'); 
    
            Route::get('change-password', 'ChangePasswordController@index')->name('change.password');
            Route::post('change-password', 'ChangePasswordController@store')->name('post.change.password');
        }
    );

untitled folder/app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProjectRequest;
use App\Project;
use App\ProjectStatus;
use App\Region;
use Illuminate\Http\Request;

class ProjectController extends Controller
{

    public function index()
    {
        $projects = Project::paginate(20);

        $data['projects'] = $projects;

        $regions = Region::get()->pluck('name', 'id');

        $data['regions'] = $regions;

        $projectStatuses = ProjectStatus::get()->pluck('name', 'id');

        $data['projectStatuses'] = $projectStatuses;

        return view('backend.project.index', $data);
    }


    public function create()
    {
        //
    }


    public function store(ProjectRequest $request)
    {
        Project::create($request->all());

        return redirect()->back()->with('success', 'Project Added Successfully!');
    }


    public function show(Project $project)
    {
        //
    }


    public function edit(Project $project)
    {
        $projects = Project::paginate(20);

        $data['projects'] = $projects;

        $data['project'] = $project;

        $regions = Region::get()->pluck('name', 'id');

        $data['regions'] = $regions;

        $projectStatuses = ProjectStatus::get()->pluck('name', 'id');

        $data['projectStatuses'] = $projectStatuses;

        return view('backend.project.edit', $data);
    }


    public function update(Request $request, Project $project)
    {
        $project->update($request->all());

        return redirect()->back()->with('success', 'Project Updated Successfully!');
    }


    public function destroy(Project $project)
    {
        $project->delete();

        return redirect()->route('projects.index')->with('success', 'Project Deleted Successfully!');
    }
}

untitled folder/resources/views/backend/project/edit.blade.php
@extends('backend.layouts.master')
@section('title', 'Edit Project')
@section('content')

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Edit Project</h2>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{route('dashboard')}}">Home</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{route('projects.index')}}">Project</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>Edit</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Edit Project</h5>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="ibox-content">
                            @if(\Session::has('success'))
                            <div class="alert alert-success">
                                <ul class="list-style-none">
                                    <li>{!! \Session::get('success') !!}</li>
                                </ul>
                            </div>
                            @endif
                            <form action="{{ route('projects.update', $project->id) }}" method="POST">
                                @csrf
                                {{ method_field('PUT') }}
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="region">Select Region *</label>
                                            <div class="form-group @error('region_id') has-error @enderror">
                                                {!! Form::select('region_id', $regions , $project->region_id,
                                                array('class' =>
                                                'form-control selectpicker','data-live-search' =>
                                                'true','placeholder'=>'Select Region')
                                                ); !!}
                                                @error('region_id')
                                                <div class="inline-errors">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="region">Select Status *</label>
                                            <div class="form-group @error('status_id') has-error @enderror">
                                                {!! Form::select('status_id', $projectStatuses , $project->status_id,
                                                array('class' =>
                                                'form-control selectpicker','data-live-search' =>
                                                'true','placeholder'=>'Select Status')
                                                ); !!}
                                                @error('status_id')
                                                <div class="inline-errors">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group @error('title') has-error @enderror">
                                            <label for="name">Title *</label>
                                            <input type="text" name="title" class="form-control"
                                                value="{{$project->title}}">
                                            @error('title')
                                            <div class="inline-errors">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Sub Title</label>
                                            <input type="text" name="sub_title" class="form-control"
                                                value="{{$project->sub_title}}">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Plant Type</label>
                                            <input type="text" name="plant_type" class="form-control"
                                                value="{{$project->plant_type}}">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Electricity Capacity</label>
                                            <input type="text" name="plant_type" class="form-control"
                                                value="{{$project->plant_type}}">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="form-group">
                                            <label for="name">Location</label>
                                            <input type="text" name="location" class="form-control"
                                                value="{{$project->location}}">
                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            <label for="name" class="display-block">&nbsp;</label>
                                            <input type="submit" class="btn btn-primary" value="Update">
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <div class="clear"></div>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="ibox-content">
                            @if(count($projects))
                            <table class="table table-striped table-bordered table-hover tooltip-suggestion">
                                <thead>
                                    <tr>
                                        <th class="text-center">#</th>
                                        <th>Region</th>
                                        <th>Status</th>
                                        <th>Title</th>
                                        <th>Sub Title</th>
                                        <th>Plant Type</th>
                                        <th>Electricity Capacity</th>
                                        <th>Location</th>
                                        <th class="text-center ProjectActionTh">Action</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach($projects as $key=>$project)
                                    <tr class="gradeX">
                                        <td class="text-center">{!! ($key+1)+(20*($projects->currentPage()-1)) !!}</td>
                                        <td>{{$project->region->name}}</td>
                                        <td>{{$project->status->name}}</td>
                                        <td>{{$project->title}}</td>
                                        <td>{{$project->sub_title}}</td>
                                        <td>{{$project->plant_type}}</td>
                                        <td>{{$project->electricity_capacity}}</td>
                                        <td>{{$project->location}}</td>
                                        <td class="action-column tooltip-suggestion">
                                            <a class="btn btn-success btn-circle"
                                                href="{{ route('projects.edit', $project->id) }}" data-toggle="tooltip"
                                                data-placement="top" title="Edit"><i class="fa fa-edit"></i></a>
                                            <form id="DeleteProject-{{$project->id}}" method="POST"
                                                action="{{ route('projects.destroy', $project->id) }}"
                                                class="action-form">
                                                @csrf
                                                {{ method_field('DELETE') }}

                                                <a href="javascript:void(0)" onclick="deleteProject({{$project->id}})"
                                                    class="btn btn-danger btn-circle" data-toggle="tooltip"
                                                    data-placement="top" title="Delete"><i class="fa fa-trash"></i></a>
                                            </form>
                                        </td>
                                    </tr>
                                    @endforeach

                                </tbody>
                            </table>
                            <div class="dataTables_paginate paging_simple_numbers">
                                {{$projects->links()}}
                            </div>
                            @else
                            <div class="text-center">
                                <h4>No project available</h4>
                            </div>
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

untitled folder/resources/views/backend/project/index.blade.php
@extends('backend.layouts.master')
@section('title', 'Project')
@section('content')

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Project</h2>
        <ol class="breadcrumb">            
            <li class="breadcrumb-item">
                <a href="{{route('dashboard')}}">Home</a>
            </li>
            <li class="breadcrumb-item active">
                <strong>Project</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>

<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            @include('backend.project.template.project-list-table')
        </div>
    </div>
</div>

@endsection