untitled folder/routes/web.php
    <?php
    
    use Illuminate\Support\Facades\Auth;
    use Illuminate\Support\Facades\Route;
    
    Auth::routes();
    
    
    Route::get('/', 'HomeController@index')->name('home');
    
    Route::group( ['prefix' => 'company-profile' ],
    
        function () {
            Route::get('/', 'Front\CompanyController@index')->name('company-profile');
            Route::get('chairman-report', 'Front\CompanyController@chairmanReport')->name('chairman-report');
            Route::get('business-principles', 'Front\CompanyController@principlesCode')->name('principles-code');
            Route::get('corporate-governance', 'Front\CompanyController@corporateGovernance')->name('corporate-governance');        
            Route::get('timeline', 'Front\CompanyController@timeline')->name('timeline');
            Route::get('board-of-directors', 'Front\CompanyController@boardOfDirectors')->name('board-of-directors');
            Route::get('management-team', 'Front\CompanyController@managementTeam')->name('management-team');
			Route::get('awards', 'Front\CompanyController@awards')->name('awards');
            }
    );

    Route::group( ['prefix' => 'management-team' ],
    
        function () {
        Route::get('/', 'Front\ManagementController@index')->name('management-team');
        Route::get('thanaphol-leelangamwong', 'Front\ManagementController@thanapholLeelangamwong')->name('thanaphol-leelangamwong');
        Route::get('santi-suanyot', 'Front\ManagementController@santiSuanyot')->name('santisuanyot');
        Route::get('phiphit-khlaisombat', 'Front\ManagementController@phiphitKhlaisombat')->name('phiphit-khlaisombat');
        Route::get('nattapong-dachanabhirom', 'Front\ManagementController@nattapongDachanabhirom')->name('nattapong-dachanabhirom');
        Route::get('palat-tittinutchanon', 'Front\ManagementController@palatTittinutchanon')->name('palat-tittinutchanon');
        Route::get('harry-brock', 'Front\ManagementController@harryBrock')->name('harry-brock');
        Route::get('john-clendon', 'Front\ManagementController@johnClendon')->name('john-clendon');
            
        }
    );
    
    Route::group( ['prefix' => 'directors' ],
    
        function () {
        Route::get('/', 'Front\DirectorsController@index')->name('directors');
        Route::get('apirag-vanich', 'Front\DirectorsController@apiragVanich')->name('apirag-vanich');
        Route::get('phortchana-manoch', 'Front\DirectorsController@phortchanaManoch')->name('phortchana-manoch');
        Route::get('kanchana-vanich', 'Front\DirectorsController@kanchanaVanich')->name('kanchana-vanich');
        Route::get('palat-tittinutchanon', 'Front\DirectorsController@palatTittinutchanon')->name('palat-tittinutchanon');
        Route::get('chantip-vanich', 'Front\DirectorsController@chantipVanich')->name('chantip-vanich');
        Route::get('prote-sosothikul', 'Front\DirectorsController@proteSosothikul')->name('prote-sosothikul');
        Route::get('john-clendon', 'Front\DirectorsController@johnClendon')->name('john-clendon');
        Route::get('suchad-chiaranussati', 'Front\DirectorsController@suchadChiaranussati')->name('suchad-chiaranussati');
        Route::get('supapang-chanlongbutra', 'Front\DirectorsController@supapangChanlongbutra')->name('supapang-chanlongbutra');
        Route::get('pramoad-phornprapha', 'Front\DirectorsController@pramoadPhornprapha')->name('pramoad-phornprapha');
        }
    );
    
    Route::group( ['prefix' => 'operations' ],
        function () {
            Route::get('/', 'Front\OperationsController@index')->name('operations');
            Route::get('estates', 'Front\OperationsController@estates')->name('estates');
            Route::get('factories', 'Front\OperationsController@factories')->name('factories');
            Route::get('nurseries', 'Front\OperationsController@nurseries')->name('nurseries');
        }
    );
    
    Route::group( ['prefix' => 'estates' ],
        function () {
            Route::get('/', 'Front\EstatesController@index')->name('estates');
            Route::get('topi', 'Front\EstatesController@topi')->name('topi');
            Route::get('siampalm', 'Front\EstatesController@siampalm')->name('siampalm');
            Route::get('akapojana', 'Front\EstatesController@akapojana')->name('akapojana');
            Route::get('nanua', 'Front\EstatesController@nanua')->name('nanua');
            Route::get('chauat', 'Front\EstatesController@chauat')->name('chauat');
            Route::get('pabon', 'Front\EstatesController@pabon')->name('pabon');
            Route::get('wannee', 'Front\EstatesController@wannee')->name('wannee');
            Route::get('lamthap', 'Front\EstatesController@lamthap')->name('lamthap');
            Route::get('cheanvanich', 'Front\EstatesController@cheanvanich')->name('cheanvanich');
            Route::get('khlongtom', 'Front\EstatesController@khlongtom')->name('khlongtom');
        }
    );
    
    Route::group( ['prefix' => 'products' ],
        function () {
    
            Route::get('/', 'Front\ProductsController@index')->name('products');
            Route::get('cpo-pko', 'Front\ProductsController@cpoPko')->name('cpo-pko');
            Route::get('seed-seedlings', 'Front\ProductsController@seedSeedlings')->name('seed-seedlings');
            Route::get('seeds', 'Front\ProductsController@seeds')->name('seeds');
            Route::get('seedlings', 'Front\ProductsController@seedlings')->name('seedlings');
            Route::get('biogas', 'Front\ProductsController@biogas')->name('biogas');
            Route::get('by-products', 'Front\ProductsController@byProducts')->name('by-products');
    
        }
    );
    
    Route::group( ['prefix' => 'investor-relations' ],
        function () {
        
            Route::get('/', 'Front\InvestorRelationsController@index')->name('investor-relations');
            Route::get('financial-information', 'Front\InvestorRelationsController@financialInformation')->name('financial-information');
            Route::get('shareholder', 'Front\InvestorRelationsController@shareholder')->name('shareholder');
            Route::get('publications', 'Front\InvestorRelationsController@publications')->name('publications');
        }
    
    );
    
    Route::group( ['prefix' => 'sustainability' ],
        function () {
            Route::get('/', 'Front\SustainabilityController@index')->name('sustainability');
            Route::get('social-sustainability', 'Front\SustainabilityController@social')->name('social');
            Route::get('environmental-sustainability', 'Front\SustainabilityController@environmental')->name('environmental');
            Route::get('economic-sustainability', 'Front\SustainabilityController@economic')->name('economic');
            Route::get('scientific-sustainability', 'Front\SustainabilityController@scientific')->name('scientific');
            Route::get('corporate-governance', 'Front\SustainabilityController@corporate')->name('corporate');
        }
    );
    
    Route::group( ['prefix' => 'media' ],
        function () {
            Route::get('/', 'Front\MediaController@index')->name('media');
            Route::get('news2008', 'Front\MediaController@news2008')->name('news2008');
            Route::get('news2007', 'Front\MediaController@news2007')->name('news2007');
            Route::get('news2006', 'Front\MediaController@news2006')->name('news2006');
        }
    );
    
    Route::group( ['prefix' => 'careers' ],
        function () {
            Route::get('/', 'Front\CareersController@index')->name('careers');
        }
    );
    
    Route::group( ['prefix' => 'contact-us' ],
        function () {
            Route::get('/', 'Front\ContactController@index')->name('contact');
            Route::get('whistleblowing', 'Front\ContactController@whistleblowing')->name('whistleblowing');
            Route::get('feedback-inquiries', 'Front\ContactController@feedbackInquiries')->name('feedback-inquiries');
        }
    );
    
    
    
    
    
    
    
    Route::get('company-awards', 'HomeController@companyAwards')->name('company-awards');
    Route::get('operation-map', 'HomeController@operationMap')->name('operation-map');
    
    Route::get('projects', 'HomeController@projects')->name('projects');
    Route::get('project-details', 'HomeController@projectDetails')->name('project-details');
    
    Route::group(
        [
            'prefix' => 'admin',
            'middleware' => ['auth']
        ],
        function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
    
            Route::resource('regions', 'RegionController');
            Route::resource('status', 'ProjectStatusController');
            Route::resource('projects', 'ProjectController'); 
    
            Route::get('change-password', 'ChangePasswordController@index')->name('change.password');
            Route::post('change-password', 'ChangePasswordController@store')->name('post.change.password');
        }
    );

untitled folder/app/Http/Controllers/RegionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\RegionRequest;
use App\Region;

class RegionController extends Controller
{

    public function index()
    {
        $regions = Region::paginate(20);

        $data['regions'] = $regions;

        return view('backend.region.index', $data);
    }


    public function create()
    {
        //
    }


    public function store(RegionRequest $request)
    {
        Region::create($request->all());

        return redirect()->back()->with('success', 'Region Added Successfully!');
    }


    public function show($id)
    {
        //
    }


    public function edit(Region $region)
    {
        $regions = Region::paginate(20);

        $data['regions'] = $regions;

        $data['region'] = $region;  

        return view('backend.region.edit', $data);
    }


    public function update(RegionRequest $request, Region $region)
    {
        $region->update($request->all());

        return redirect()->back()->with('success', 'Region Updated Successfully!');
    }


    public function destroy(Region $region)
    {
        $region->delete();

        return redirect()->route('regions.index')->with('success', 'Region Deleted Successfully!');
    }
}

untitled folder/resources/views/backend/region/template/region-list-table.blade.php
<div class="ibox float-e-margins">

    <div class="ibox-title">
        <div class="titleWrap">
            <h5>Region</h5>
        </div>
    </div>

    <div class="row">
        <div class="col-md-4">
            <div class="ibox-content">
                @if(\Session::has('success'))
                <div class="alert alert-success">
                    <ul class="list-style-none">
                        <li>{!! \Session::get('success') !!}</li>
                    </ul>
                </div>
                @endif
                <form action="{{ route('regions.store') }}" method="POST">
                    @csrf

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group @error('name') has-error @enderror">
                                <label for="name">Name</label>
                                <input type="text" name="name" class="form-control" value="{{old('name')}}">
                                @error('name')
                                <div class="inline-errors">{{ $message }}</div>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-2">
                            <div class="form-group">
                                <label for="name" class="display-block">&nbsp;</label>
                                <input type="submit" class="btn btn-primary" value="Add">
                            </div>
                        </div>
                    </div>
                </form>
                <div class="clear"></div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="ibox-content">
                @if(count($regions))
                <table class="table table-striped table-bordered table-hover tooltip-suggestion">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th>Region</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($regions as $key=>$region)
                        <tr class="gradeX">
                            <td class="text-center">{!! ($key+1)+(20*($regions->currentPage()-1)) !!}</td>
                            <td>{{$region->name}}</td>
                            <td class="action-column tooltip-suggestion text-center">
                                <a class="btn btn-success btn-circle" href="{{ route('regions.edit', $region->id) }}"
                                    data-toggle="tooltip" data-placement="top" title="Edit"><i
                                        class="fa fa-edit"></i></a>
                                <form id="DeleteRegion-{{$region->id}}" method="POST"
                                    action="{{ route('regions.destroy', $region->id) }}" class="action-form">
                                    @csrf
                                    {{ method_field('DELETE') }}
                                    <a href="javascript:void(0)" onclick="deleteRegion({{$region->id}})"
                                        class="btn btn-danger btn-circle" data-toggle="tooltip" data-placement="top"
                                        title="Delete"><i class="fa fa-trash"></i></a>
                                </form>
                            </td>
                        </tr>
                        @endforeach

                    </tbody>
                </table>
                <div class="dataTables_paginate paging_simple_numbers">
                    {{$regions->links()}}
                </div>
                @else
                <div class="text-center">
                    <h4>No region available</h4>
                </div>
                @endif
            </div>
        </div>
    </div>
</div>